### ISSUE TITLE
script errors mess up the output of the xml reporter

### ISSUE THREAD

**Issue by cromega** [busterjs/buster#265] opened 2012-08-16 12:31 UTC
when something causes a yellow error, it ends up in wrong parts of the ouput. its true for the dots reporter as well, the yellow lines should be written somewhere after the failing test name, not among the dots.
but its especially critical with the xml reporter where those lines break the xml structure:

...
&lt;/testsuite>
[1m[33mUncaught exception: Unable to get property 'name' of undefined or null reference[0m
[1m[33mUncaught exception: ./stuff.js:168 Uncaught TypeError: Cannot read property 'name' of undefined[0m
&lt;testsuite errors="0" tests="20" time="0.003" failures="0" name="Firefox 13.0.1, Windows 7">
...

also, the error lines shouldn't be truncated

**Comment by GCheung55** [comment] 2015-01-22 00:46
May be dupe of https://github.com/busterjs/buster/issues/439.

**Comment by dwittner** [comment] 2015-07-14 06:46
This issue is now handled in #439.

**Closed by dwittner** 2015-07-14 06:46 UTC
Labels: Bug
